services:
  rustapp:
    container_name: rustapp
    image: anantduhan/rustapp:latest
    build:
      context: ./backend
      dockerfile: rust.Dockerfile
      args:
        DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata: {}
